### ISSUE TITLE
As a user, I want to chat with random people. So I click the "Match button", I can chat with other people.

### ISSUE THREAD

**Issue by jweng6** [xlab-classes/cse442-spring2022-team-heart#16]
Acceptance test 1: 

1) After login into the account, there will have a matching button. 2) Click the match button, there will start a chat with random people
3) Click the end chat button, it will end the chat.

**Comment by Chuanlong21** [comment]
Acceptance test 1:

1. Users can go to the web(http://cheshire.cse.buffalo.edu:8080/web_war/SignIn.html)
2. Users should login to their account with username and password.
3. Users can click the rocket logo to match with other people.
4. Users can chat with others.

**Comment by Chuanlong21** [comment]
Acceptance test 2:

1. Users can go to the web (http://cheshire.cse.buffalo.edu:8080/web_war/SignIn.html)
2. Users can click the register button to set up their accounts.
3. it's required to fill in username, email , password, and confirm password.
4. go to the email box users just entered.
5. enter the verification code we just sent to you
6. click the complete button to go to the next page.
7. fill in the interest page, then click the done button
8. Users can click the rocket logo to match with other people
9. Users can chat with others now
