### ISSUE TITLE
As a user, I want to see the static login/registration page locally.

### ISSUE THREAD

**Issue by HaifengXiao-29** [xlab-classes/cse442-spring2022-team-heart#23]

**Comment by Chuanlong21** [comment]
Task test 1:

1. Go to the localhost on the laptop
2. Click the HTML file to open static pages of the app
3. Check if there is a login page
4. If you see the login page, you can put your email/username and password into the box and click the "Sign In" button
5. Once you click the "Sign In" button, you will see a page that has a rocket image in the center, and two arrows on the bottom, and if you click the left arrow, you will go back to the previous webpage, if you click the right arrow, you will go to the chat page
6. On the chat page, you can see a "heart" on the top left, and says "Chat" inside the heart, if you click the "heart" image, you will go back to the "Match" page
