### ISSUE TITLE
Host the web on the SEAS server

### ISSUE THREAD

**Issue by Chuanlong21** [xlab-classes/cse442-spring2022-team-heart#24]

**Comment by HaifengXiao-29** [comment]
Task test #1:
1. Open website (https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442m/cse442-spring2022-team-heart)
2. See if our code is there

**Comment by HaifengXiao-29** [comment]
Task test #2:

1. Open the terminal and connect to the server
2. Check there is a folder contains our code
