### ISSUE TITLE
Logout functionality should be implemented

### ISSUE THREAD

**Issue by HaifengXiao-29** [xlab-classes/cse442-spring2022-team-heart#34]

**Comment by Chuanlong21** [comment]
Task test 1:
when our team member set the server open

1. open the web (http://cheshire.cse.buffalo.edu:8080/web_war/SignIn.html)
2. check if you see the sign in page,
3. either enter username and password to signin or click register button to set up an new account.
4. remember you can always click the left arrow to go back to the previous page.
5. when you are in the chat page, you can click the heart logo to logout.
