### ISSUE TITLE
Create a page where user puts info for matching process (Frontend, Backend and DB)

### ISSUE THREAD

**Issue by HaifengXiao-29** [xlab-classes/cse442-spring2022-team-heart#38]

**Comment by Chuanlong21** [comment]
Task test 1:

1. Go to web (http://cheshire.cse.buffalo.edu:8080/web_war/SignIn.html)
2. check if there is a register button then click it
3. fill in the username, password, email, and confirm password.
4. click the next button to go to the next page
5. check if there is an email in your email box.
6. enter the verification code.
7. click the complete button to go to the info page 
8. check if you can drag your interest to the earth.
9. click the done button to finish setting.
