### ISSUE TITLE
As a user, I want to set up my account, so I click the Register button

### ISSUE THREAD

**Issue by haoxiang215** [xlab-classes/cse442-spring2022-team-heart#6]

**Comment by haoxiang215** [comment]
Acceptance test 1:

Users will first go to the website
Then they will see "Create Account ->" below the "Sign in " button
After they click the "Create Account ->" button, they will jump to a new website and has "Username", "Password", "Email", and "Verification Code", users can either register with their email or they can choose their own username.
If users want to sign up with their email, users can enter their email in the email input box, and click next.
Users can go to their email and see the verification code and enter it into the verification code box.
Users then click the complete button and they complete the process.
Acceptance test 2:

Users will first go to the website
Then they will see "Create Account ->" below the "Sign in " button
After they click the "Create Account ->" button, they will jump to a new website and has "Username", "Password", "Email", and "Verification Code", users can either register with their email or they can choose their own username.
If users want to sign up with their own username and password, they can enter the username and password they want into the boxes.
Users then click the complete button and they complete the process.

**Comment by Chuanlong21** [comment]
Acceptance test 2:

1. Users will first go to the website
2. Then they will see "Create Account ->" below the "Sign in " button
3. After they click the "Create Account ->" button, they will jump to a new website and has "Username", "Password", "Email", and "Verification Code", users can either register with their email or they can choose their own username.
4. If users want to sign up with their own username and password, they can enter the username and password they want into the boxes.
5. Users then click the complete button and they complete the process.

**Comment by jweng6** [comment]
Acceptance test 1:

1. Users will first go to the website(http://cheshire.cse.buffalo.edu:8080/web_war/signUp.html)
2. Then they will see "Create Account ->" below the "Sign in " button
3. After they click the "Create Account ->" button, they will jump to a new website and has "Username", "Password", "Email", and "Verification Code". 

4.Users need to register with their email and  username that has not been register yet.

5. After finish to put the email,username,password and confirmed password, user need to click "complete button". That our server will send the vertify code to user's email.

6. After click the "complete button", there will jump to vertify page.So user need to open their email to check the verity code.Then user need to enter the correct verify code to the input box.

7. Once the verify code is correct. Then all done for register.

**Comment by jweng6** [comment]
Acceptance test 2:

1. Users will first go to the website(http://cheshire.cse.buffalo.edu:8080/web_war/signUp.html)
2. Then they will see "Create Account ->" below the "Sign in " button
3. After they click the "Create Account ->" button, they will jump to a new website and has "Username", "Password", "Email", and "Verification Code". 

4.Users need to register with their email and  username that has not been register yet.

5. After finish to put the email, username, password and confirmed password, user need to click "complete button". That our server will send the verify code to user's email.

6. After click the "complete button", there will jump to verify page. So user need to open their email to check the verity code. Then user need to enter the correct verify code to the input box.

7. If user don't receive the verify code or wanna resend the verify code, user can click "resend code "button, that server will resend a new verity code to user.

8. Once the verify code is correct. Then all done for register.
